// Copyright (c) 2026 DevOnBike.
// This file is part of DevonBike Overfit.
// DevonBike Overfit is licensed under the GNU AGPLv3.
// For commercial licensing options, contact: devonbike@gmail.com

using System.Text.Json.Serialization;
using DevOnBike.Overfit.Anomalies.Contracts;

namespace DevOnBike.Overfit.Cli
{
    /// <summary>
    /// Source-generated reader for the anomaly guard's configuration file.
    ///
    /// <para><b>Why not <c>IConfiguration.Bind</c>, which would be one line.</b> Binding walks the type with
    /// reflection, so it carries IL2026 and IL3050 and cannot survive a Native-AOT publish — and this binary
    /// is exactly that. A source-generated context does the same job with the shape known at compile time, so
    /// the trimmer keeps what is needed and nothing else.</para>
    ///
    /// <para>Case-insensitive on purpose: the same file is expected to be written by hand, generated by a
    /// Helm template, or lifted out of an <c>appsettings</c> section, and those three disagree about casing.
    /// A silently unbound property here is a threshold that quietly became zero.</para>
    /// </summary>
    [JsonSourceGenerationOptions(
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = System.Text.Json.JsonCommentHandling.Skip,
        AllowTrailingCommas = true)]
    [JsonSerializable(typeof(AnomalyGuardConfigFile))]
    internal sealed partial class AnomalyGuardJsonContext : JsonSerializerContext
    {
    }
}
