// Copyright (c) 2026 DevOnBike.
// This file is part of DevonBike Overfit.
// DevonBike Overfit is licensed under the GNU AGPLv3.
// For commercial licensing options, contact: devonbike@gmail.com

using DevOnBike.Overfit.Anomalies.Contracts;
using DevOnBike.Overfit.Anomalies.Monitoring;

namespace DevOnBike.Overfit.Tests.Anomalies
{
    /// <summary>
    /// A <c>LearnedState</c> payload written <b>before</b> the peer-novelty section existed must still restore
    /// history, calibration, labels and suppressions untouched.
    ///
    /// <para><b>The fixture was produced by the pre-change code and is checked in, which is the whole point.</b>
    /// <c>Tests/test_fixtures/anomalies/learned-state-pre-an-d1.txt</c> was written by
    /// <c>LearnedState.Write</c> as it stood before this task, then frozen. A fixture generated by the new
    /// code would agree with the new code by construction and could not fail — the exact lesson
    /// <c>FloorCalibrator</c>'s <c>#windows</c> bug taught, where a file from an older build was silently read
    /// as satisfying a gate it had never recorded.</para>
    ///
    /// <para>It deliberately carries every awkward feature of the format at once: thirteen calibration rows, a
    /// <c>~</c>-marked custom channel, the <c>#windows</c> marker, a label whose reason contains an escaped
    /// tab, and a live suppression.</para>
    /// </summary>
    public sealed class LearnedStatePeerNoveltyCompatibilityTests
    {
        private static string Payload()
        {
            var path = Path.Combine(
                AppContext.BaseDirectory, "test_fixtures", "anomalies", "learned-state-pre-an-d1.txt");

            return File.ReadAllText(path);
        }

        /// <summary>All four pre-existing sections survive a payload that has no fifth one.</summary>
        [Fact]
        public void AnOlderPayloadStillRestoresEverySection()
        {
            var restored = LearnedState.Read(Payload());

            Assert.Equal(7, restored.Calibrator.Propose()[0].Windows);
            Assert.Contains("myapp_queue_depth", restored.Calibrator.CustomChannels);
            Assert.Equal(2, restored.Labels.Count);
            Assert.Equal(1, restored.Suppressions.Count);

            var memory = restored.Calibrator.Propose()[(int)MetricIndex.MemoryWorkingSetBytes];

            Assert.True(memory.PeerGapMax > 0.0, "the calibration's peer-gap maximum did not survive");

            // The label's reason carries a tab, which is the field separator — escaping is the only reason
            // this round-trips at all, and the novelty section must not disturb it.
            Assert.Contains(
                restored.Labels.Labels,
                l => l.Reason.Contains('\t', StringComparison.Ordinal));
        }

        /// <summary>An older payload leaves the novelty part cold-starting, not throwing.</summary>
        [Fact]
        public void AnOlderPayloadLeavesTheNoveltySectionEmpty()
        {
            var restored = LearnedState.Read(Payload());

            Assert.Equal(string.Empty, restored.PeerNovelty);

            var tracker = PeerNoveltyTracker.Read(restored.PeerNovelty, PeerNoveltyOptions.Daily);

            Assert.Equal(0, tracker.TrackedPods);
        }

        /// <summary>
        /// Text in the peer-novelty section must never reach the suppression store.
        ///
        /// <para><b>Written because the obvious round-trip test below could not fail on it.</b> Mutating
        /// <c>LearnedState.Read</c> so the suppression section runs to the end of the payload — swallowing the
        /// novelty section whole — left <c>AddingTheNoveltySectionDoesNotDisturbTheOthers</c> green, because a
        /// real novelty row's third column is a metric key and never parses as a magnitude, so
        /// <c>SuppressionStore.Read</c> silently skipped it. The boundary was therefore untested and only
        /// accidentally safe.</para>
        ///
        /// <para>The row below is shaped like a suppression on purpose. If the boundary ever moves, a phantom
        /// mute appears from nowhere — a suppression nobody created, silencing a signal, which is the worst
        /// failure this subsystem has.</para>
        /// </summary>
        [Fact]
        public void NoveltySectionTextNeverReachesTheSuppressionStore()
        {
            var payload = Payload()
                          + "\n### peer-novelty\n"
                          + "1788134400\t99\t0.5\tghost-pod\tghost-workload\tGhostSignal\tnot a suppression\n";

            var restored = LearnedState.Read(payload);

            Assert.Equal(1, restored.Suppressions.Count);
            Assert.DoesNotContain(
                restored.Suppressions.Suppressions,
                s => string.Equals(s.Signal, "GhostSignal", StringComparison.Ordinal));
        }

        /// <summary>
        /// Rewriting the older payload with a novelty section and reading it back changes nothing about the
        /// other four — the direction an upgrade actually travels.
        ///
        /// <para><b>This does not on its own pin the section boundary</b> — see
        /// <see cref="NoveltySectionTextNeverReachesTheSuppressionStore"/>, which does.</para>
        /// </summary>
        [Fact]
        public void AddingTheNoveltySectionDoesNotDisturbTheOthers()
        {
            var before = LearnedState.Read(Payload());
            var tracker = new PeerNoveltyTracker(PeerNoveltyOptions.Daily);

            tracker.Observe(
                "lab-workload-7765564ff6-pj7r8",
                new DateTimeOffset(2026, 8, 5, 6, 0, 0, TimeSpan.Zero),
                MetricIndex.MemoryWorkingSetBytes,
                1.02e7,
                new DateTimeOffset(2026, 8, 6, 8, 0, 0, TimeSpan.Zero),
                1_000_000.0);

            var rewritten = LearnedState.Write(
                before.History, before.Calibrator, before.Labels, before.Suppressions, tracker);

            var after = LearnedState.Read(rewritten);

            Assert.Equal(before.Labels.Count, after.Labels.Count);
            Assert.Equal(before.Suppressions.Count, after.Suppressions.Count);
            Assert.Equal(
                before.Calibrator.Propose()[(int)MetricIndex.MemoryWorkingSetBytes].PeerGapMax,
                after.Calibrator.Propose()[(int)MetricIndex.MemoryWorkingSetBytes].PeerGapMax,
                6);
            Assert.Contains("myapp_queue_depth", after.Calibrator.CustomChannels);

            Assert.Equal(
                1,
                PeerNoveltyTracker.Read(after.PeerNovelty, PeerNoveltyOptions.Daily).TrackedPods);
        }
    }
}
